### ISSUE TITLE
第16回 - 会場を手配する

### ISSUE THREAD

**Issue by aibax** [jaws-ug-kanazawa/jaws-ug-kanazawa.github.io#15]
- [ ] 会場を決める
- [ ] 会場を予約する
- [ ] 利用料を支払う

**Comment by PharaohKJ** [comment]
第16回 - doorkeeper でイベントを作成・公開する #10 

に含まれているのですがわかりにくいようですね。タイトル変えます。

**Comment by aibax** [comment]
あ、ゴメン。そっちにあったのか。見落としてました。

**Comment by aibax** [comment]
じゃこっちクローズ。
