### ISSUE TITLE
JAWS-DAYS 2016 報告会

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/jaws-ug-kanazawa.github.io#3]
- [x] 日時決め
- 場所決め
  - [x] 会場
  - [ ] 懇親会場
- [x] 内容決め
- [x] ゲスト決め
- 広報
  - [x] Facebookページ
  - [x] [JAWS-UG 公式ページ](http://jaws-ug.jp/bc/kanazawa/)
  - [x] JAWS-UG 公式 Google カレンダー
  - [x] AWSJ 公式ページ「ユーザーグループイベント」への掲載依頼
- 参加受付
  - [x] doorkeeper

**Comment by PharaohKJ** [comment]
日時は 4/9 (第2土曜)に決定

**Comment by aibax** [comment]
内容について

今回のテーマの「JAWS DAYS 報告会」と、その他のサービスの状況を踏まえるとこんな感じでどうでしょう。たたき台です。

1. Introduction : 祝 JAWS-UG金沢 5周年 / AWS・S3 10周年 / 東京リージョン 5周年
2. AWSの全体的な紹介 + アップデート
3. JAWS DAYS 2016 参加レポート
4. Amazon S3
5. LT

**Comment by yuuitiro** [comment]
- 会場 c8cafe（クリパカフェ） セミナールーム 金沢市西念1丁目3-9 （旧IDC校舎）
- 参加費 500円

**Comment by PharaohKJ** [comment]
@aibax 内容についてですが、それでよいと思います。

参加レポートは私30分〜1時間ぐらい、S3については、私のブログがS3+cloudfrontで動いていて、
その収支ほか、を15分〜30分ぐらいはしゃべられると思います。

**Comment by aibax** [comment]
@PharaohKJ
3番のJAWS DAYS の参加レポートですが、僕はHackDayにどっぷりで他見てないし、 @yuuitiro さんはお客さんに捕まってたしw なので、一番たくさん見れた加藤さんにお願いするのが良いかと思うんですがいかがでしょうか？

@yuuitiro 
ゆういちろうさん、この中で喋れそうなテーマ、もしくはここに無いけど喋りたいテーマ、何かあります？

僕はre:Moteの時にS3の全体的な話をしたんだけど、参加者が今回とほとんど被らなそうなので、その時の内容をアップデートしてもう一度やる形で4番のS3担当するか、資料入手して1番、2番あたりをやるかかなー。

**Comment by aibax** [comment]
タイムスケジュールですが、各セッション40分だとこんな感じ。
いかがでしょ？

13:00 開場・準備・受付
13:15 開会
13:30-14:10 セッション1
14:20-15:00 セッション2
15:10-15:50 セッション3
16:00-16:40 セッション4
16:50-17:30 LT（10分x4本くらいは可能）
（後片付け・退室）
18:30-21:00 懇親会

**Comment by PharaohKJ** [comment]
よいと思います。そしてこのスケジュールは毎回使えるのではないでしょうか。

私は

3. JAWS DAYS 2016 参加レポート

を担当します。あとLT枠でS3にからんで、Jekyll + S3 + Cloudfront のblogホスティング収支について話したいと思います。

**Comment by aibax** [comment]
JAWS-UG富山の石倉さんが喋れるかもという事だったので1セッション打診。

**Comment by yuuitiro** [comment]
僕はまだ内容決めてないけど、愛している Route53 で何かネタを考えたいと思います。

**Comment by aibax** [comment]
セッションですが、以下の4つ出ましたのでこれでいかがでしょうか。

13:30-14:10 セッション1 : JAWS DAYS 2016 参加レポート（仮） → 加藤さん（ @PharaohKJ ）
14:20-15:00 セッション2 : 愛している Route53 で何か（仮）→ ゆういちろうさん（ @yuuitiro ）
15:10-15:50 セッション3 : 「祝10周年 超定番サービス Amazon S3 の魅力」 → 相羽（ @aibax ）
16:00-16:40 セッション4 : 内容調整中 → 石倉さん（JAWS-UG富山）

順番は仮の案なので変更可。でも加藤さんはネタ的にやっぱり最初が良いかな。

**Comment by PharaohKJ** [comment]
私はこれでいいです + 最初でOKです。

タイトルは「俺とJAWS-DAYS 2016」
内容は「加藤が聴講したセッションの内容を紹介し、今後について考察したことを発表します。」でお願いします。

**Comment by aibax** [comment]
最初に、AWSとは、JAWS-UGとは、JAWS-UG金沢とはって感じのイントロがいるよね。
開会のあいさつと一緒にやればよいかな？

**Comment by aibax** [comment]
@PharaohKJ LTの方のタイトルもよろー。

**Comment by PharaohKJ** [comment]
あいさつからの紹介についてはゼヒその段取りでお願いします。

LTのタイトルは「俺とブログ運営 S3+cloudfrontを使って」でお願いします。

**Comment by aibax** [comment]
@PharaohKJ @yuuitiro 
勉強会のページにセッションタイトルを掲載しようと思います。
スピーカー欄に記載する「所属」と「お名前」を教えて下さい。
あと、順番について変更希望があれば受け付けます。

**Comment by yuuitiro** [comment]
@aibax  
順番については、加藤さんが場を暖めて頂いてその後ということでＯＫですｗ
スピーカー欄に書く名前は 「松本雄一郎」「JAWS-UG金沢＆富山（仮）」にしてもらえますか？

**Comment by aibax** [comment]
@PharaohKJ @yuuitiro 
セッションの内容を更新しました。こんな感じでいかがでしょうか？
http://jaws-ug.jp/es/kanazawa09/

@yuuitiro 
「JAWS-UG 富山」は（仮）だと状況が分からないかと思ったので（準備中）という形で書いてみました。あと、所属に会社名とか入れます？

**Comment by PharaohKJ** [comment]
:+1:

**Comment by aibax** [comment]
AWSイベントページ（ http://aws.amazon.com/jp/about-aws/events/ ）への掲載依頼完了。
水曜日17時締切で翌週火曜日までに掲載されます。

**Comment by yuuitiro** [comment]
@aibax 「JAWS-UG 富山（準備中）」の件、了解です。僕はいまのところ所属に会社はなしでＯＫ！

**Comment by yuuitiro** [comment]
昨日はお疲れ様でした！
この Issue は 終了ってことで閉じますね。
