### ISSUE TITLE
平日勉強会5月

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/jaws-ug-kanazawa.github.io#5]
- 日時決め
  - [x] 開催日
  - [x] 開催時間
- [ ] 場所決め
  - [ ] 会場
  - [ ] 懇親会場
- [ ] 内容決め
- [ ] ゲスト決め
- 広報
  - [ ] Facebookページ
  - [ ] [JAWS-UG 公式ページ](http://jaws-ug.jp/bc/kanazawa/)
  - [ ] JAWS-UG 金沢 Google カレンダー
  - [ ] JAWS-UG 公式 Google カレンダー
  - [ ] AWSJ 公式ページ「ユーザーグループイベント」への掲載依頼

(
AWS-Hub(meetup、飲み会)月 - 週末実施月 - 平日開催月

の3ヶ月単位ローテで行うことにする。
- [ ] 上記をウェブページに記載すること
)

**Comment by aibax** [comment]
- 開催日 : 5/12
- 開催時間 : 19:00 - 21:00

**Comment by PharaohKJ** [comment]
http://bit.ly/jawsug-kanazawa-tasks

こちらにいったん移動します。 close.
