### ISSUE TITLE
AWS Cloud Roadshow 2016 金沢 JAWS-UGの会

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/jaws-ug-kanazawa.github.io#8]
- [ ] 内容決め
- [ ] 担当決め
- [ ] 各種手配
- [ ] doorkeeper公開

18:00本会終わりなので 18:30 - 21:00 の間を決める。
今のところ

18:30 30min 事例紹介1
19:00 30min 事例紹介2
19:30 10min 休憩
19:40 30min 事例紹介3
20:10 30min パネル
20:40 終了までご歓談

こんな感じでしたっけ。

**Comment by PharaohKJ** [comment]
事例1 某市の案件については発表できないか交渉中です。本日(07/11)メール送付予定
事例2 CfKについては本日(07/11)先方に提示、打ち合わせ予定

**Comment by PharaohKJ** [comment]
事例1 は OK でました。
事例2 は ペンディング。

いったん LT大会とします。

18:30 - 18:45 JAWS-UG金沢について 相羽さん
18:45 - 19:00 AWS小島さま
19:00 - 19:15 エヴァンジェリストさま
19:15 - 19:30 かほく市公式子育てアプリ「子育てにゃんでもトーク」事例 ファランクスウェア加藤
19:30 - 19:40 休憩
LT大会開始
19:40 - 枠1
19:50 - 枠2
20:00 - 枠3
20:10 - 俺とブログコスト by ファランクスウェア加藤
20:20 - 枠5
20:30 - 枠6
20:40 終了までご歓談

**Comment by hishisa** [comment]
LTのネタ以下のような感じでお願い致します。
発表順は枠3ぐらいが良いです。

弊社のAWS利用状況 by 石崎弘之 日本オープンシステムズ(JOPS)

**Comment by PharaohKJ** [comment]
ありがとうございます。本家のページが公開されたので、内容などの議論についてはあちらで行いましょう。

https://jawsug-kanazawa.doorkeeper.jp/events/48056

**Comment by PharaohKJ** [comment]
終わったのでいったんclose
